### ISSUE TITLE
Host field value cannot be `localhost`

### ISSUE THREAD

**Issue by johnjohndoe** [flaper87/meclipse#18]
I cannot configure `localhost` as the **host** to configure the database connection. Only `127.0.0.1` worked for me. Please add advices in the "New Connection Wizard" or implement the option to use `localhost`.

**Comment by philnate** [comment]
I can't reproduce this error. I can insert localhost as host just fine with the 0.0.5 Version as well as with the latest ba50dc51256e5eb854a7a0d0cdb8326666373a14. Can you please describe what you tried and what error you received?

**Comment by johnjohndoe** [comment]
Strange! Today, I neither can reproduce the phenomenon. Sry.

**Comment by philnate** [comment]
No problem, maybe the host was down or something else was going wrong in Bit and Byte land :)
