### ISSUE TITLE
URL update no working

### ISSUE THREAD

**Issue by angelbotto** [flaper87/meclipse#25]
:-1:  no working the url for update eclipse plugin, :+1:  fixed please :smile:

**Comment by philnate** [comment]
I've added an update site at: flaper87.github.com/meclipse/updates please verify that this is working for you.

**Comment by angelbotto** [comment]
http://flaper87.github.com/meclipse/updates/ 404 page not found :crying_cat_face:

**Comment by philnate** [comment]
Yes browsing this you'll get a 404, but does it work when you enter this URL as repository URL for Meclipse? this should work, maybe I'm gonna add some page telling what's up.

**Comment by angelbotto** [comment]
working ... :+1:  

thanks
