### ISSUE TITLE
Update site link does not work?

### ISSUE THREAD

**Issue by kokujin** [flaper87/meclipse#26]
The update site link does not work, could someone check this please? Thanks

**Comment by philnate** [comment]
Sorry forgot to update to latest location: http://flaper87.github.com/meclipse/updates/

**Comment by kokujin** [comment]
That link above is also not found, 404

**Comment by philnate** [comment]
This is the updatesite. Set this as URL for your Eclipse update site and it will work. I.e. http://flaper87.github.com/meclipse/updates/site.xml would give you some content. The problem is that there's no index.html or whatever to display for you, so it looks like it's not working.
